image: rust

stages:
  - test
  - publish

test:
  stage: test
  script:
  - cargo test

publish:
  stage: publish
  script:
  - cargo login $CARGO_TOKEN
  - cargo package
  - cargo publish
  only:
  - tags
