[package]
name = "tma"
version = "0.1.0"
description = "The tmux Automator"
repository = "https://github.com/ndarilek/tma"
readme = "README.md"
keywords = ["tmux"]
license = "MIT"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]

[dependencies]
getopts = "0.2"
serde = "0.9"
serde_derive = "0.9"
toml = "0.3"
