resource_types:

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:

- name: repo
  type: git
  source:
    uri: https://github.com/ndarilek/tma
    branch: master

- name: release_repo
  type: git
  source:
    uri: https://github.com/ndarilek/tma
    branch: master
    tag_filter: v[0-9]*

- name: gh_release
  type: github-release
  source:
    owner: ndarilek
    repository: tma
    access_token: {{github_access_token}}

jobs:

- name: build
  public: true
  plan:

  - get: repo
    trigger: true

  - task: run build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: jimmycuadra/rust}
      inputs:
        - name: repo
      run:
        path: sh
        args:
          - -exc
          - |
            cd repo
            cargo build

- name: release
  public: true
  plan:

  - get: release_repo
    trigger: true

  - task: release
    config:
      params:
        CARGO_TOKEN: {{cargo_token}}
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: jimmycuadra/rust}
      inputs:
        - name: repo
      outputs:
        - name: release
      run:
        path: sh
        args:
          - -exc
          - |
            cd repo
            cargo login ?$CARGO_TOKEN"
            cargo publish
            cargo build --release
            git describe --tag >../release/version
            echo tma_linux_amd64 >../release/filename
            cp target/release/tma ../release

  - put: gh_release
    params:
      name: release/filename
      tag: release/version
      globs:
      - release/tma
